POST http://localhost:5000/user/login
Content-Type: application/json

{
    "name": "Admin",
    "password": "Admin"
}

###

GET http://localhost:5000/allTask
Content-Type: application/json

###
POST http://localhost:5000/allTask/delete/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjY4NzA3NzU0NjksImlkIjoxLCJpYXQiOjE2MjY4NjcxNzV9.D9hScRvt-oTdzIKCgRek_g9mIIvdTmnYsWN-ek7Szwo
Content-Type: application/json

###

GET http://localhost:5000/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjY4NjYwMDIzODcsImlkIjoyLCJpYXQiOjE2MjY4NjI0MDJ9.Wf97GkmiOad4Cewzv_HMCS2wvcr0j4k9-bjo9i6jtHM

###
POST http://localhost:5000/allTask
Authorization: Bearer eyJhbGciOUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjY4NjYwMDIzODcsImlkIjoyLCJpYXQiOjE2MjY4NjI0MDJ9.Wf97GkmiOad4Cewzv_HMCS2wvcr0j4k9-bjo9i6jtHM
Content-Type: application/json

{
    "body": "ciao"
}